name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.0

    - run: go install golang.org/x/tools/cmd/goimports@latest
    - run: go install mvdan.cc/gofumpt@latest
    - run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Format and check
      run: |
        goimports -w .
        gofumpt -w .
        if [ -n "$(git diff)" ]; then
          git diff
          exit 1
        fi

    - run: go build -v ./...
    - run: go vet -v ./...
    - run: staticcheck ./...
